name: deploy-model-training-pipeline

on: 
  workflow_dispatch:
jobs:
  get-config:
      uses: CoursesTF
      with:
        file_name: config-infra-prod.yml
  register-environment:
      needs: get-config
      uses: CoursesTF
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}     
        environment_file:  mlops/azureml/train/train-env.yml
        conda_file: data-science/environment/train-conda.yml
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          
  register-dataset:
    needs: get-config
    uses: CoursesTF
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      name: taxi-data
      data_file: mlops/azureml/train/data.yml
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS}}
      
  create-compute:
      needs: [get-config,register-environment,register-dataset]
      uses: CoursesTF
      with:
        cluster_name: cpu-cluster
        size: Standard_E4s_v3
        min_instances: 0
        max_instances: 4
        cluster_tier: low_priority
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}     
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      
  run-pipeline:
      needs: [get-config,register-environment,create-compute,register-dataset]
      uses: CoursesTF
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}     
        parameters-file:  mlops/azureml/train/pipeline.yml
        job-name: test
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}
